apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gyzc2lxao-go 
  janus-idp.io/tekton: gyzc2lxao-go
  backstage.io/kubernetes-id: gyzc2lxao-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gyzc2lxao-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml